config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships

  resources :beer_clubs

  resources :users

  resources :beers

  resources :breweries

  resources :styles

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'

  get 'signin', to: 'sessions#new'
  
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]

  post 'places', to:'places#search'

  resources :ratings, :only => [:index, :new, :create, :destroy]

  resources :sessions, only: [:new, :create]

  get 'beerlist', to:'beers#list'

  get 'ngbeerlist', to:'beers#nglist'

    get 'brewerylist', to:'breweries#nglist'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
	has_many :memberships
    has_many :members, through: :memberships, source: :user

    def to_s
       "#{name}"
    end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_admin, except: [:index, :show, :edit, :update]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.user = current_user
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer_club }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.text_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club), class:'btn btn-warning white-text' if current_user %></td>
        <td><%= link_to 'Destroy', beer_club, class:'btn btn-danger white-text', method: :delete, data: { confirm: 'Are you sure?' } if current_is_admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<h1>
  <%= @beer_club.name %>
</h1>

<p>
  Founded <%= @beer_club.founded %> |
  <%= @beer_club.city %>
</p>

<h2>
	Memebers
</h2>

<ul>
	<% @beer_club.memberships.each do |mship| %>
	   <li>
	   	   <%= link_to mship.user, mship.user %>
	   </li>
	<% end %>
</ul>
<br><br>


<% if current_user %>
<% if @beer_club.memberships - current_user.memberships == @beer_club.memberships || @beer_club.memberships.empty? %>
  <%= form_for(@membership) do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit value:"Join the Club" %>
  <% end %>
  <% end %>
<% end %>



<%= link_to 'Back', beer_clubs_path, class:"btn white-text btn-info" %>
<%= "|" if current_is_admin %>
<%= edit_and_destroy_buttons(@beer_club) %>